theme: jekyll-theme-minimal
title: [Anna Bell O'Keefe's DS Portfolio]
description: [
- Programming Languages: Java :coffee: , Python :snake: , C :floppy_disk: , Bash :mag_right: , and Assembly x86 :building_construction:	.
- Applied skills: Object-oriented programming, discrete mathematics, statistical analysis, project management, curriculum building, foreign language translation, international communication, small-business management and start-up, sales, technical writing and leadership.
- Previous work experience: Director of Music at Daybreak Academy in South Jordan, UT.
- Other skills, interests and academic experience: Ancient Greek language, philosophy, history of science and mathematics; Romance languages and comparative literature; Entrepreneurship; Piano and percussion performance; Music production; Education and curriculum design. 
]

plugins:
  - jemoji

permalink: /blog/:year/:month/:day/:title
